### ISSUE TITLE
Inquiry about exposed login and password file

### ISSUE THREAD

**Issue by Yoanndp** [whoisdsmith/c0d3bl0ck-obsidian#1]
@whoisdsmith,

I noticed that a file containing login and password information is currently exposed publicly on this repository ([Logins.md](https://github.com/whoisdsmith/c0d3bl0ck-obsidian/raw/main/Folders/Logins.md)). I wanted to open this issue to confirm if this is intentional or if it's a mistake that needs to be addressed.

If this was not intentional, I suggest adding a line to the .gitignore file to exclude this file from being tracked, or even better, removing the file completely. This will prevent any potential security breaches or data leaks in the future.

Thank you for your attention to this matter.

**Comment by whoisdsmith** [comment]
Damnnnnnn Thank You!! I definitely didnt realize that file was in my public vault!!

I will address the issue right now!

Thanks Again!

**Comment by whoisdsmith** [comment]
I had many personal identifying files in here, thank you for bringing this to my attention!

**Comment by Yoanndp** [comment]
Be aware that git keeps a history of all activity in a repository. This means that even if files have been deleted, they are still present in the history. I recommend you to either recreate a new repository or make it private
